https://www.hackerrank.com/contests/tugas-1-tif-a/challenges

https://www.hackerrank.com/contests/livecode-1-tif-a/challenges
https://www.hackerrank.com/contests/livecode-2-tif-a/challenges

https://www.hackerrank.com/contests/tugas-2-tif-a/challenges

http://www.hackerrank.com/utp

https://www.hackerrank.com/contests/latihan-seleksi-kondisi-1604663052/challenges
https://www.hackerrank.com/live-coding-bab-input-output-praktikum-pemdas-si-c
https://www.hackerrank.com/contests/peanuts-7-0/challenges
https://www.hackerrank.com/contests/si-e-2020-lc-2/challenges/mendapatkan-informasi-dari-nim/submissions/code/1328040798

https://www.hackerrank.com/contests/evaluasi-pra-utp/challenges
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-5/challenges
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-6/challenges
https://www.hackerrank.com/tugas-1-pemdas-si-a
https://www.hackerrank.com/contests/utp-pemdas-si-a/challenges
https://www.hackerrank.com/live-coding-2-pemdas-si-a
https://www.hackerrank.com/lc-2-tif-e
https://www.hackerrank.com/contests/pemdas-tifb-ifelse/challenges
https://www.hackerrank.com/latihan2-tif-e
https://www.hackerrank.com/tugas-1-tif-e
https://www.hackerrank.com/praktikum-1-tif-e
https://www.hackerrank.com/contests/latihan-looping-tif-d/challenges
https://www.hackerrank.com/contests/utp-pemrograman-dasar-sistem-informasi-kelas-c/challenges/cek-protokol-kesehatan/submissions/code/1328143792
https://www.hackerrank.com/live-coding-bab-2-seleksi-kondisi-tekkom-clink
https://www.hackerrank.com/contests/lc-ifelse-tif-d/challenges
https://www.hackerrank.com/utp-tif-f-2020
https://www.hackerrank.com/live-coding-input-output-tif-f-2020

https://www.hackerrank.com/contests/utp-discord-filkom-ub/challenges/aim-lab-bangjago/copy-from/1328188766
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-utp/challenges
https://www.hackerrank.com/si-e-2020-utp
https://www.hackerrank.com/contests/utp-pemdas-tif-e/challenges
https://www.hackerrank.com/utp-pti-a-2020
https://www.hackerrank.com/contests/utp-tif-f-2020/challenges
https://www.hackerrank.com/contests/tugas-3-tif-a/challenges
https://www.hackerrank.com/lc-loop-tif-d
https://www.hackerrank.com/live-coding-perulangan-tif-f-2020
https://www.hackerrank.com/evaluasi-looping
https://www.hackerrank.com/contests/tugas-4-tif-a/challenges
https://www.hackerrank.com/contests/lc-3-tif-e/challenges
https://www.hackerrank.com/contests/praktikum-9-pemrograman-dasar-si-b/challenges
https://www.hackerrank.com/contests/live-coding-4-pemdas-si-a/challenges
https://www.hackerrank.com/utp-tif-d
https://www.hackerrank.com/contests/bank-soal-pemdas/challenges
https://www.hackerrank.com/contests/algoritma-dan-struktur-data-tif-20202021-semester-ganjil/challenges
https://www.hackerrank.com/live-coding-array-tif-f-2020
https://www.hackerrank.com/contests/praktikum-10-pemrograman-dasar-si-b/challenges
https://www.hackerrank.com/livecode-4-tif-a
https://www.hackerrank.com/latihan-array-tif-d
https://www.hackerrank.com/contests/live-coding-array-1607079840/challenges
https://www.hackerrank.com/remidi-perulangan-tif-f
https://www.hackerrank.com/contests/livecode-5-tif-a/challenges
https://www.hackerrank.com/contests/tugas-5-tif-a/challenges
https://www.hackerrank.com/contests/lc-array-method-tif-e/challenges
https://www.hackerrank.com/contests/live-coding-bab-5-method-si-c/challenges
https://www.hackerrank.com/lc-method
https://www.hackerrank.com/lc-method-tif-d
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-12/challenges

www.hackerrank.com/tulungihsan01
www.hackerrank.com/tulung-ihsan-2
https://www.hackerrank.com/contests/latihan-uap-discord-filkom/challenges
https://www.hackerrank.com/contests/latihanpraktikumtifgifelse/challenges
https://www.hackerrank.com/contests/extend-if-else/challenges
https://www.hackerrank.com/contests/praktikum-if-else/challenges
https://www.hackerrank.com/contests/lc-2-tif-e/challenges
https://www.hackerrank.com/contests/latihan2-tif-e/challenges
https://www.hackerrank.com/contests/utppemdas-tif-g-2020/challenges
https://www.hackerrank.com/contests/utp-pemdas-tif-e/challenges
https://www.hackerrank.com/contests/latihan-perulangan-tif-g/challenges
https://www.hackerrank.com/contests/perulangan-tif-g/challenges
https://www.hackerrank.com/contests/latihan-array-1606394729/challenges
https://www.hackerrank.com/contests/live-coding-array-tif-g/challenges
https://www.hackerrank.com/contests/latihan-method-1607250937/challenges
https://www.hackerrank.com/contests/live-coding-method-tif-g-1/challenges

https://www.hackerrank.com/contests/uap-tif-d/challenges
https://www.hackerrank.com/contests/uap-tif-f-2020/challenges
https://www.hackerrank.com/contests/uap-pemdas-tif-e-2020/challenges
https://www.hackerrank.com/contests/uap-tif-a-2020/challenges
https://www.hackerrank.com/contests/uap-pemrograman-dasar-tif-c/challenges




(Punya https://github.com/Kimitozuki/HackerRank/blob/main/Link%20HackerRank%20Smst%201.txt)
Input Output
==================================================
https://www.hackerrank.com/contests/tugas-1-tif-a/challenges
https://www.hackerrank.com/contests/livecode-1-tif-a/challenges
https://www.hackerrank.com/contests/live-coding-bab-input-output-praktikum-pemdas-si-c/challenges
https://www.hackerrank.com/contests/peanuts-7-0/challenges
https://www.hackerrank.com/tugas-1-pemdas-si-a
https://www.hackerrank.com/tugas-1-tif-e
https://www.hackerrank.com/praktikum-1-tif-e
https://www.hackerrank.com/tugas-1-pemdas-si-a

Seleksi Kondisi
==================================================
https://www.hackerrank.com/contests/tugas-2-tif-a/challenges
https://www.hackerrank.com/contests/livecode-2-tif-a/challenges
https://www.hackerrank.com/contests/latihan-seleksi-kondisi-1604663052/challenges
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-5/challenges
https://www.hackerrank.com/contests/crystal-7-0/challenges
https://www.hackerrank.com/contests/latihanpraktikumtifgifelse/challenges
https://www.hackerrank.com/contests/extend-if-else/challenges
https://www.hackerrank.com/contests/praktikum-if-else/challenges
https://www.hackerrank.com/contests/lc-2-tif-e/challenges
https://www.hackerrank.com/contests/latihan2-tif-e/challenges
https://www.hackerrank.com/contests/si-e-2020-lc-2/challenges
https://www.hackerrank.com/contests/tugas-2-tif-a/challenges
https://www.hackerrank.com/contests/lc-ifelse-tif-d/challenges
https://www.hackerrank.com/latihan2-tif-e
https://www.hackerrank.com/lc-2-tif-e
https://www.hackerrank.com/contests/pemdas-tifb-ifelse/challenges
https://www.hackerrank.com/live-coding-2-pemdas-si-a

Perulangan
==================================================
https://www.hackerrank.com/contests/livecode-3-tif-a/challenges
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-6/challenges
https://www.hackerrank.com/contests/latihan-perulangan-tif-g/challenges
https://www.hackerrank.com/contests/perulangan-tif-g/challenges
https://www.hackerrank.com/remidi-perulangan-tif-f/challenges
https://www.hackerrank.com/contests/live-coding-3-pemdas-si-a/challenges
https://www.hackerrank.com/contests/praktikum-9-pemrograman-dasar-si-b/challenges
https://www.hackerrank.com/tugas-3-tif-a/challenges
https://www.hackerrank.com/contests/lc-3-tif-e/challenges
https://www.hackerrank.com/evaluasi-looping
https://www.hackerrank.com/live-coding-perulangan-tif-f-2020
https://www.hackerrank.com/lc-loop-tif-d
https://www.hackerrank.com/contests/latihan-looping-tif-d/challenges

UTP
==================================================
https://www.hackerrank.com/utp/challenges
https://www.hackerrank.com/ujian-tengah-praktikum-pemrograman-dasar-si-b/challenges
https://www.hackerrank.com/contests/evaluasi-pra-utp/challenges
https://www.hackerrank.com/contests/utp-tif-a-2020/challenges
https://www.hackerrank.com/contests/utp-discord-filkom-ub/
https://www.hackerrank.com/utp-discord-filkom-ii
https://www.hackerrank.com/contests/utppemdas-tif-g-2020/challenges
https://www.hackerrank.com/contests/utp-pemdas-tif-e/challenges
https://www.hackerrank.com/utp-tif-d/challenges
https://www.hackerrank.com/contests/utp-tif-f-2020/challenges
https://www.hackerrank.com/utp-pti-a-2020
https://www.hackerrank.com/si-e-2020-utp
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-utp/challenges
https://www.hackerrank.com/contests/utp-pemrograman-dasar-sistem-informasi-kelas-c/challenges
https://www.hackerrank.com/contests/utp-pemdas-si-a/challenges

Array
==================================================
https://www.hackerrank.com/contests/live-coding-4-pemdas-si-a/challenges
https://www.hackerrank.com/contests/tugas-4-tif-a/challenges
https://www.hackerrank.com/contests/live-coding-array-1607079840/challenges
https://www.hackerrank.com/contests/latihan-array-1606394729/challenges
https://www.hackerrank.com/contests/tulungihsan01/challenges
https://www.hackerrank.com/contests/tulung-ihsan-2/challenges
https://www.hackerrank.com/latihan-array-tif-d/challenges
https://www.hackerrank.com/contests/livecode-4-tif-a/challenges
https://www.hackerrank.com/live-coding-array-tif-f-2020/challenges


Method
==================================================
https://www.hackerrank.com/contests/tugas-5-tif-a/challenges
https://www.hackerrank.com/contests/tugas-5-pemdas-si-a/challenges
https://www.hackerrank.com/contests/latihan-method-1607250937/challenges
https://www.hackerrank.com/contests/live-coding-method-tif-g-1/challenges
https://www.hackerrank.com/contests/praktikum-pemdas-si-d-12/challenges
https://www.hackerrank.com/lc-method-tif-d/challenges
https://www.hackerrank.com/lc-method/challenges
https://www.hackerrank.com/contests/live-coding-bab-5-method-si-c/challenges
https://www.hackerrank.com/contests/lc-array-method-tif-e/challenges

UAP
==================================================
https://www.hackerrank.com/contests/uap-tif-d/challenges
https://www.hackerrank.com/contests/uap-tif-f-2020/challenges
https://www.hackerrank.com/contests/uap-pemdas-tif-e-2020/challenges
https://www.hackerrank.com/contests/uap-tif-a-2020/challenges
https://www.hackerrank.com/contests/uap-pemrograman-dasar-tif-c/challenges
https://www.hackerrank.com/contests/latihan-uap-discord-filkom/challenges

Any
==================================================
https://www.hackerrank.com/contests/cp-oemoem-2020/challenges
https://www.hackerrank.com/contests/bank-soal-pemdas/challenges
